Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08e2d37b6a0129927
      Tags:
        - Key: "Name"
          Value: !Join ["-",[instance, from, cloudformation]]
